#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS:   H:2 num:nil toc:nil \n:nil ::t |:t -:t f:t *:t <:t

#+OPTIONS:   tex:t  d:nil todo:t pri:nil tags:not-in-toc
#+BEGIN_HTML
---
category: computer science and enginneering
layout: post
title: "Common UML Tools"
description: ""
tags: [tools]
---

#+END_HTML


* UML Graph

  [[http://yuml.me/diagram/scruffy/activity/draw][yUML]] IS an online service FOR creating class AND use CASE
  diagrams. The service can be called from your blog or web page (with
  the textual description as part of the URL)to automatically display
  the image when accessing it. 

[[http://www.umlgraph.org/][UML Graph]] automatically draws class AND sequence diagrams. FOR the
class diagrams, uses a Java-based syntax complemented by javadoc
tags. Running the UmlGraph doclet ON the specification will generate a
Graphviz diagram specification. FOR sequence diagrams uses a different
approach (AND this IS one aspect I don’t like about the tool, you are
basically working with two different tools here). Pic macros are used
to define objects and method invocations. Then, the pic2plot program
processes the macros to generate PNGs and other graphic
formats. LightUML integrates UMLGraph in Eclipse.





