#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS:   H:2 num:nil toc:nil \n:nil ::t |:t -:t f:t *:t <:t

#+OPTIONS:   tex:t  d:nil todo:t pri:nil tags:not-in-toc
#+BEGIN_HTML

#+END_HTML

* process pair[fn:1]

  Tandem's system created process pairs consisting of a primary
  process and a backup process. First, the primary process would
  begin, then clone itself elsewhere as a backup. Guardian would send
  an initial message to the backup process, "telling" the process its
  status as a backup. Finally, the backup would become passive and
  accept messages from either Guardian or the primary process. When an
  error occurred, Guardian would automatically re-route a message from
  a failing component to a functioning one. Checkpointing and
  synchronization were important to maintain "uptimes" measured in
  years, as opposed to the typical systems of the day that failed
  every few days.

* high availablility

* fault toleration

* past-the-end

According to the c++ reference[fn:2] 
In all the c++ containers, they include a member function
function iterator end(), and the function returns an iterator
referring to the past-the-end element in the set container.

The past-the-end element is the theoretical element that would follow
the last element in the set container. It does not point to any
element, and thus shall not be dereferenced.

past-the-end 的中文意思是： 在 终点/结尾/最后 之后。或紧随终点/结尾/最
后。

* Pattern matching
Pattern matching consists of specifying patterns to which some data
should conform and then checking to see if it does and deconstructing
the data according to those patterns. Reference "Learning You a Haskell"




[fn:1] Fault Tolerance in Tandem Computer Systems
[fn:2] http://www.cplusplus.com/reference/set/set/end/

